apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: lanchonete-container
          image: grupo27/foodtech:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"  # This is the CPU limit
            requests:
              cpu: "0.5"  # This is the CPU reques
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-svc:5432/postgres"
            - name: GATEWAY_DATA_PAYMENT_NOTIFICATION
              value: "https://affb5f4a552504f6bb3b4c644fd75f3c-391679596.us-east-1.elb.amazonaws.com/pedidos/notifications"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SERVER_PORT
              value: "8080"
            - name: TOKEN_APP
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: token


