apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
  labels:
    app: lanchonete
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: lanchonete
